#!/usr/bin/env python3
"""
scan-repo-status.py — Brood orchestrator's "repo-centric" lens

扫描三个 sibling org 目录下的所有仓库，输出一张紧凑的状态表到
docs/REPO_STATUS.md，让 Brood 拥有 65 个 repo 的全量健康度视野（而不是
只看 In Progress 任务关联的 15 个）。

输出列：
  org / repo / branch / ahead/behind / 未提交 / 最近提交 / 距今天 / tag / 静默标记

静默判定：
  🟢 ≤ 30 天    🟡 31-90 天    🔴 91-365 天    💤 > 365 天

Usage:
  python3 scripts/scan-repo-status.py [--json|--markdown(default)]
"""
import os
import subprocess
import sys
import json
from datetime import datetime

ORG_DIRS = [
    (os.path.expanduser("~/Dev/aastar"),   "AAStarCommunity", "aastar"),
    (os.path.expanduser("~/Dev/auraai"),   "AuraAIHQ",        "auraai"),
    (os.path.expanduser("~/Dev/mycelium"), "MushroomDAO",     "mycelium"),
]

TODAY = datetime.now().date()


def run(cmd, cwd=None, timeout=15):
    """Run a command, return stdout stripped (empty string on failure)."""
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return r.stdout.strip()
    except Exception:
        return ""


def days_since(date_str):
    """Days from given YYYY-MM-DD to TODAY."""
    if not date_str:
        return None
    try:
        d = datetime.strptime(date_str, "%Y-%m-%d").date()
        return (TODAY - d).days
    except Exception:
        return None


def staleness_flag(days):
    if days is None:
        return "?"
    if days <= 30:
        return "🟢"
    if days <= 90:
        return "🟡"
    if days <= 365:
        return "🔴"
    return "💤"


def scan_repo(path):
    """Extract a single repo's state."""
    branch = run(["git", "-C", path, "branch", "--show-current"]) or "—"

    # Ahead/behind vs origin/<branch>
    ahead_behind = "—"
    if branch and branch != "—":
        rev = run(
            ["git", "-C", path, "rev-list", "--left-right", "--count",
             f"{branch}...origin/{branch}"]
        )
        if rev and "\t" in rev:
            a, b = rev.split("\t")
            ahead_behind = f"{a}→{b}"

    # Uncommitted files
    porcelain = run(["git", "-C", path, "status", "--porcelain"])
    uncommitted = len(porcelain.splitlines()) if porcelain else 0

    # Last commit date
    last_commit = run(["git", "-C", path, "log", "-1", "--format=%ad", "--date=short"])

    # Last tag (if any)
    tag = run(["git", "-C", path, "describe", "--tags", "--abbrev=0"]) or "—"

    days = days_since(last_commit)

    return {
        "branch": branch,
        "ahead_behind": ahead_behind,
        "uncommitted": uncommitted,
        "last_commit": last_commit or "—",
        "days_since": days,
        "tag": tag,
        "flag": staleness_flag(days),
    }


def scan_all():
    """Walk all three org dirs, return list of dicts."""
    repos = []
    for base, org_full, org_short in ORG_DIRS:
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            path = os.path.join(base, name)
            if not os.path.isdir(os.path.join(path, ".git")):
                continue
            info = scan_repo(path)
            info.update({"org": org_short, "org_full": org_full, "repo": name})
            repos.append(info)
    return repos


def to_markdown(repos):
    """Render as markdown table grouped by org."""
    today = TODAY.strftime("%Y-%m-%d")
    out = [
        "# Repo Status — 仓库视角全量摘要",
        "",
        f"> Auto-generated by `scripts/scan-repo-status.py` · 最后扫描: **{today}**",
        "> 跟 `backlog/docs/doc-7`（task 视角）互补。本表覆盖**所有** 65 个仓库，包括 dormant / 候选启动 / 边缘仓库。",
        "",
        "**静默判定**：🟢 ≤30 天 · 🟡 31-90 天 · 🔴 91-365 天 · 💤 >365 天",
        "",
    ]

    # Statistics first
    flag_count = {"🟢": 0, "🟡": 0, "🔴": 0, "💤": 0, "?": 0}
    for r in repos:
        flag_count[r["flag"]] = flag_count.get(r["flag"], 0) + 1

    out += [
        "## 健康度统计",
        "",
        f"- 🟢 活跃（≤30 天）：**{flag_count['🟢']}** 个",
        f"- 🟡 减速（31-90 天）：**{flag_count['🟡']}** 个",
        f"- 🔴 静默（91-365 天）：**{flag_count['🔴']}** 个",
        f"- 💤 长期静默（>365 天）：**{flag_count['💤']}** 个",
        f"- 总计：{len(repos)} 个仓库",
        "",
    ]

    by_org = {}
    for r in repos:
        by_org.setdefault(r["org"], []).append(r)

    for org_short, org_full, _ in [
        ("aastar", "AAStarCommunity", None),
        ("auraai", "AuraAIHQ", None),
        ("mycelium", "MushroomDAO", None),
    ]:
        rs = by_org.get(org_short, [])
        if not rs:
            continue
        out += [
            f"## {org_full} ({len(rs)} 个仓库)",
            "",
            "| Flag | Repo | Branch | 本地→远端 | 未提交 | 最近提交 | 距今 | Tag |",
            "|:----:|:-----|:-------|:---------:|:------:|:--------:|:----:|:----|",
        ]
        # Sort: active first, then by stale-days asc
        rs_sorted = sorted(rs, key=lambda x: (x["days_since"] if x["days_since"] is not None else 99999))
        for r in rs_sorted:
            days_disp = f"{r['days_since']}d" if r["days_since"] is not None else "?"
            unc_disp = f"⚠️ {r['uncommitted']}" if r["uncommitted"] > 0 else "—"
            out.append(
                f"| {r['flag']} | `{r['repo']}` | {r['branch']} | {r['ahead_behind']} | "
                f"{unc_disp} | {r['last_commit']} | {days_disp} | {r['tag']} |"
            )
        out.append("")

    # Attention list — only flag真信号: stale, many uncommits, or out-of-sync with remote
    def needs_attention(r):
        if r["flag"] in ["🔴", "💤"]:
            return True
        if r["uncommitted"] >= 3:
            return True
        if r["ahead_behind"] not in ["—", "0→0"]:
            return True
        return False
    attention = [r for r in repos if needs_attention(r)]
    if attention:
        out += [
            "## ⚠️ 关注列表",
            "",
            "需要 orchestrator 主动判断「是否要重新激活 / 推上日程」的仓库：",
            "",
            "| Flag | Repo | 关注原因 |",
            "|:----:|:-----|:---------|",
        ]
        for r in attention:
            reasons = []
            if r["flag"] in ["🔴", "💤"]:
                reasons.append(f"静默 {r['days_since']} 天")
            if r["uncommitted"] > 0:
                reasons.append(f"未提交 {r['uncommitted']} 文件")
            if r["ahead_behind"] not in ["—", "0→0"]:
                reasons.append(f"本地↔远端 {r['ahead_behind']}")
            out.append(f"| {r['flag']} | `{r['org']}/{r['repo']}` | {' · '.join(reasons)} |")
        out.append("")

    out += [
        "---",
        "",
        "## 使用说明",
        "",
        "本文件由 `scripts/scan-repo-status.py` 自动生成。重新扫描：",
        "",
        "```bash",
        "python3 scripts/scan-repo-status.py            # 写入本文件",
        "python3 scripts/scan-repo-status.py --json     # 输出 JSON 给程序用",
        "```",
        "",
        "与 `backlog/docs/doc-7 - 📊-Progress-Report.md` 的区别：",
        "- 本文件 = **repo 视角**，覆盖全部 65 个仓库（含 dormant）",
        "- doc-7 = **task 视角**，只覆盖有 In Progress backlog 任务关联的仓库",
        "",
        "两者互补，orchestrator 同时读才能完整判断状态。",
    ]
    return "\n".join(out)


def main():
    repos = scan_all()
    if "--json" in sys.argv:
        print(json.dumps(repos, indent=2, ensure_ascii=False))
        return

    md = to_markdown(repos)
    out_path = os.path.expanduser("~/Dev/Brood/docs/REPO_STATUS.md")
    with open(out_path, "w") as f:
        f.write(md)
    print(f"✅ Wrote {out_path}")
    print(f"   {len(repos)} repos scanned")
    flag_count = {}
    for r in repos:
        flag_count[r["flag"]] = flag_count.get(r["flag"], 0) + 1
    print(f"   🟢{flag_count.get('🟢',0)}  🟡{flag_count.get('🟡',0)}  🔴{flag_count.get('🔴',0)}  💤{flag_count.get('💤',0)}")


if __name__ == "__main__":
    main()
